# Generated by Django 3.0.2 on 2020-01-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('colors', models.TextField()),
                ('sizes', models.TextField()),
                ('images', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
