# Generated by Django 3.0.2 on 2020-01-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_parse_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
